version: '3.8'
services:
  service-registry:
    build: ../service-registry/
    image: service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - craftnetwork
    restart: unless-stopped

  api-gateway:
    build: .
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    networks:
      - craftnetwork
    restart: unless-stopped

networks:
  craftnetwork:

# docker-compose up