version: '3.8'
services:
  keycloak-dev:
    container_name: keycloak-dev
    image: "quay.io/keycloak/keycloak:latest"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [ "start-dev", "--http-port=8090" ]
    ports:
      - "8090:8090"
    restart: unless-stopped

# docker compose -f docker-compose-keycloack.yml build
# docker compose -f docker-compose-keycloack.yml up -d
# docker compose -f docker-compose-keycloack.yml down