version: '3.2'
services:
  keycloak-web:
    container_name: keycloak-web
    image: "quay.io/keycloak/keycloak:25.0.1"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8090:8080"
    networks:
      - frontnetwork

networks:
  frontnetwork:

# docker-compose up
