apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: SERVER_PORT
              value: "8084"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://mariadb-comment:3306/dbcomments
            - name: SPRING_DATASOURCE_USERNAME
              value: comment
            - name: SPRING_DATASOURCE_PASSWORD
              value: comment
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          image: gmorena/comment-service
          name: comment-service
          ports:
            - containerPort: 8084
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: comment-service
  type: NodePort

# kubectl apply -f comment-service.yaml
# kubectl delete svc/comment-service
# kubectl delete deployment.apps/comment-service