apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampler-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampler-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sampler-service
    spec:
      containers:
        - env:
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://mariadb-sampler:3306/dbsamplers
            - name: SPRING_DATASOURCE_USERNAME
              value: sampler
            - name: SPRING_DATASOURCE_PASSWORD
              value: sampler
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          image: gmorena/sampler-service
          name: sampler-service
          ports:
            - containerPort: 8083
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: sampler-service
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: sampler-service
  type: NodePort

# kubectl apply -f sampler-service.yaml
# kubectl delete svc/sampler-service
# kubectl delete deployment.apps/sampler-service