version: '3.8'
services:
  service-registry:
    build: ../service-registry/
    image: service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - craftnetwork
    restart: unless-stopped

  api-gateway:
    build: ../api-gateway/
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - sampler-service
    networks:
      - craftnetwork
    restart: unless-stopped

  mariadb-sampler:
    container_name: mariadb-sampler
    image: "mariadb"
    ports:
      - "3306:3306"
    volumes:
      - sampler-data:/var/lib/mariadb/data
    networks:
      - craftnetwork
    environment:
      MARIADB_DATABASE: dbsamplers
      MARIADB_USER: sampler
      MARIADB_PASSWORD: sampler
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      restart: unless-stopped

  sampler-service:
    build: .
    image: sampler-service
    container_name: sampler-service
    ports:
      - "8083:8083"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - service-registry
      - mariadb-sampler
    networks:
      - craftnetwork
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb-sampler:3306/dbsamplers
      - SERVER_PORT=8083
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

networks:
  craftnetwork:

volumes:
  sampler-data:

# docker-compose up