version: '3.8'
services:
  service-registry:
    build: .
    image: service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    restart: unless-stopped

# docker-compose up
