apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: comment-service
  name: comment-service
spec:
  containers:
    - env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: SERVER_PORT
          value: "8084"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mariadb://mariadb-comment:3306/dbcomments
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
      image: gmorena/comment-service
      name: comment-service
      ports:
        - containerPort: 8084
          protocol: TCP
  restartPolicy: OnFailure
