apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: front-dev-pvc1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: front-dev-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: front-dev
    spec:
      containers:
        - env:
            - name: AUTH_KEYCLOAK_ID
              value: craftclient
            - name: AUTH_KEYCLOAK_ISSUER
              value: http://host.docker.internal:8090/realms/craftrealm
            - name: AUTH_KEYCLOAK_SECRET
              value: bqANx87hQ2bALhqtjqglWAGCLQW8ITmi
            - name: AUTH_URL
              value: http://localhost:3000/api/auth
            - name: NEXT_APP_API_BASE_URL
              value: http://api-gateway:8080
            - name: NEXT_APP_DEFAULT_PAGE_NUMBER
              value: "1"
            - name: NEXT_APP_DEFAULT_PAGE_SIZE
              value: "1"
          image: gmorena/front-dev
          name: front-dev
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: front-dev-cm0
            - mountPath: /app/node_modules
              name: front-dev-storage1
            - mountPath: /app/.next
              name: front-dev-storage2
      volumes:
        - configMap:
            name: front-dev-cm0
          name: front-dev-cm0
        - name: front-dev-storage1
          persistentVolumeClaim:
            claimName: front-dev-pvc1
        - name: front-dev-storage2
          persistentVolumeClaim:
            claimName: front-dev-pvc2
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: front-dev
spec:
  selector:
    app: front-dev
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer

  # kubectl create -f front-dev.yaml
  # kubectl port-forward svc/front-dev 3000:3000
  # kubectl delete svc/front-dev
  # kubectl delete deployment.apps/front-dev
