apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: front-dev
  name: front-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: front-dev
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: front-dev
    spec:
      containers:
        - env:
            - name: AUTH_KEYCLOAK_ID
              value: craftclient
            - name: AUTH_KEYCLOAK_ISSUER
              value: http://host.docker.internal:8090/realms/craftrealm
            - name: AUTH_KEYCLOAK_SECRET
              value: bqANx87hQ2bALhqtjqglWAGCLQW8ITmi
            - name: AUTH_URL
              value: http://localhost:3000/api/auth
            - name: NEXT_APP_API_BASE_URL
              value: http://api-gateway:8080
            - name: NEXT_APP_DEFAULT_PAGE_NUMBER
              value: "1"
            - name: NEXT_APP_DEFAULT_PAGE_SIZE
              value: "1"
          image: gmorena/front-dev
          name: front-dev
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: front-dev-cm0
            - mountPath: /app/node_modules
              name: front-dev-claim1
            - mountPath: /app/.next
              name: front-dev-claim2
      restartPolicy: Always
      volumes:
        - configMap:
            name: front-dev-cm0
          name: front-dev-cm0
        - name: front-dev-claim1
          persistentVolumeClaim:
            claimName: front-dev-claim1
        - name: front-dev-claim2
          persistentVolumeClaim:
            claimName: front-dev-claim2
