apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sampler-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-sampler
spec:
  selector:
    matchLabels:
      app: mariadb-sampler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb-sampler
    spec:
      containers:
        - env:
            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
              value: "true"
            - name: MARIADB_DATABASE
              value: dbsamplers
            - name: MARIADB_PASSWORD
              value: sampler
            - name: MARIADB_USER
              value: sampler
          image: mariadb
          name: mariadb-sampler
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: sampler-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: sampler-storage
          persistentVolumeClaim:
            claimName: sampler-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-sampler
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb-sampler

# kubectl apply -f mariadb-sampler.yaml
# kubectl delete svc/mariadb-sampler
# kubectl delete deployment.apps/mariadb-sampler