apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-user
spec:
  selector:
    matchLabels:
      app: mariadb-user
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb-user
    spec:
      containers:
        - env:
            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
              value: "true"
            - name: MARIADB_DATABASE
              value: dbusers
            - name: MARIADB_PASSWORD
              value: user
            - name: MARIADB_USER
              value: user
          image: mariadb
          name: mariadb-user
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: user-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: user-storage
          persistentVolumeClaim:
            claimName: user-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-user
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mariadb-user

# kubectl apply -f mariadb-user.yaml
# kubectl delete svc/mariadb-user
# kubectl delete deployment.apps/mariadb-user