apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mariadb-comment
  name: mariadb-comment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb-comment
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mariadb-comment
    spec:
      containers:
        - env:
            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
              value: "true"
            - name: MARIADB_DATABASE
              value: dbcomments
            - name: MARIADB_PASSWORD
              value: comment
            - name: MARIADB_USER
              value: comment
            - name: restart
              value: unless-stopped
          image: mariadb
          name: mariadb-comment
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mariadb/data
              name: comment-data
      restartPolicy: Always
      volumes:
        - name: comment-data
          persistentVolumeClaim:
            claimName: comment-data
