apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: user-data
  name: user-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
