version: '3.8'
services:
  service-registry:
    build: ../service-registry/
    image: service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - craftnetwork
    restart: unless-stopped

  api-gateway:
    build: ../api-gateway/
    image: api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - comment-service
      - user-service
    networks:
      - craftnetwork
    restart: unless-stopped

  mariadb-comment:
    container_name: mariadb-comment
    image: "mariadb"
    ports:
      - "3306:3306"
    volumes:
      - comment-data:/var/lib/mariadb/data
    networks:
      - craftnetwork
    environment:
      MARIADB_DATABASE: dbcomments
      MARIADB_USER: comment
      MARIADB_PASSWORD: comment
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      restart: unless-stopped

  comment-service:
    build: ../comment-service/
    image: comment-service
    container_name: comment-service
    ports:
      - "8084:8084"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - service-registry
      - mariadb-comment
      - rabbitmq
    networks:
      - craftnetwork
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb-comment:3306/dbcomments
      - SERVER_PORT=8084
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - RABBITMQ_HOST=rabbitmq

  mariadb-user:
    container_name: mariadb-user
    image: "mariadb"
    ports:
      - "3307:3306"
    volumes:
      - user-data:/var/lib/mariadb/data
    networks:
      - craftnetwork
    environment:
      MARIADB_DATABASE: dbusers
      MARIADB_USER: user
      MARIADB_PASSWORD: user
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      restart: unless-stopped

  user-service:
    build: .
    image: user-service
    container_name: user-service
    ports:
      - "8085:8085"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - service-registry
      - mariadb-user
      - rabbitmq
    networks:
      - craftnetwork
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb-user:3306/dbusers
      - SERVER_PORT=8085
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - RABBITMQ_HOST=rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - craftnetwork
    restart: unless-stopped

networks:
  craftnetwork:

volumes:
  comment-data:
  user-data:
  rabbitmq-data:

# docker-compose up