name: craft_CI_test_backend

on:
  push:
    branches:
      - "main"

jobs:

# Job to build docker images
  build_and_push_craftsman:
     name: Build and push craftsman image to Docker Hub
     runs-on: windows-latest

     steps:
       - name: Check out the repo
         uses: actions/checkout@v3

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1

       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build and push craftsman
         uses: docker/build-push-action@v2
         with:
           context: /home/runner/work/TAASS-2324_artigianato/TAASS-2324_artigianato/craftsman-service/
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/craftsman-service
