name: craft_CI_backend
# Missing api-gateway and service-registry microservices as they are supposed to be more stable
on:
  push:
    branches:
      - "main"

jobs:

# Jobs to build docker images, one for each microservice (image), so they can execute in parallel

# Job to build the image for craftsman microservice
  build_and_push_craftsman:
     name: Build and push craftsman image to Docker Hub
     runs-on: ubuntu-latest

     steps:
       - name: Check out the repo
         uses: actions/checkout@v3

       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3

       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build and push craftsman
         uses: docker/build-push-action@v6
         with:
           context: /home/runner/work/TAASS-2324_artigianato/TAASS-2324_artigianato/craftsman-service/
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/craftsman-service

# Job to build the image for sampler microservice
  build_and_push_sampler:
     name: Build and push sampler image to Docker Hub
     runs-on: ubuntu-latest

     steps:
       - name: Check out the repo
         uses: actions/checkout@v3

       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3

       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build and push sampler
         uses: docker/build-push-action@v6
         with:
           context: /home/runner/work/TAASS-2324_artigianato/TAASS-2324_artigianato/sampler-service/
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/sampler-service

# Job to build the image for craftstore microservice
  build_and_push_craftstore:
     name: Build and push craftstore image to Docker Hub
     runs-on: ubuntu-latest

     steps:
       - name: Check out the repo
         uses: actions/checkout@v3

       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3

       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build and push craftstore
         uses: docker/build-push-action@v6
         with:
           context: /home/runner/work/TAASS-2324_artigianato/TAASS-2324_artigianato/craftstore-service/
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/craftstore-service

# Job to build the image for comment microservice
  build_and_push_comment:
     name: Build and push comment image to Docker Hub
     runs-on: ubuntu-latest

     steps:
       - name: Check out the repo
         uses: actions/checkout@v3

       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3

       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build and push comment
         uses: docker/build-push-action@v6
         with:
           context: /home/runner/work/TAASS-2324_artigianato/TAASS-2324_artigianato/comment-service/
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/comment-service

# Job to build the image for user microservice
  build_and_push_user:
     name: Build and push user image to Docker Hub
     runs-on: ubuntu-latest

     steps:
       - name: Check out the repo
         uses: actions/checkout@v3

       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3

       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build and push user
         uses: docker/build-push-action@v6
         with:
           context: /home/runner/work/TAASS-2324_artigianato/TAASS-2324_artigianato/user-service/
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service
