name: craft_CI_frontend

on:
  push:
    branches:
      - "main"

jobs:

# Job to build docker images
  build_and_push_frontend:
     name: Build and push frontend image (for production) to Docker Hub
     runs-on: ubuntu-latest

     steps:
       - name: Check out the repo
         uses: actions/checkout@v3

       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3

       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build and push frontend (for production)
         uses: docker/build-push-action@v6
         with:
           # add-hosts: host.docker.internal:host-gateway
           context: /home/runner/work/TAASS-2324_artigianato/TAASS-2324_artigianato/frontend/
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/front-prod
